apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fylo
spec:
  type: ClusterIP
  selector: { app: fylo-backend }
  ports:
    - { name: http, port: 9090, targetPort: 9090 }
    - { name: websocket, port: 9091, targetPort: 9091 }
